FROM    alpine:3.22.0

RUN     apk update && apk add nginx && apk add vim && apk add curl && mkdir -p /etc/nginx/ssl && apk add openssl

RUN     mkdir -p /var/www/html

RUN     openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/CN=login.42.fr/UID=login" 

# RUN     chmod 755 /var/www/html

# RUN     chown -R www-data:www-data /var/www/html

CMD     [ "nginx", "-g", "daemon off;" ]
# EXPOSE  3000

# pour dockerfile wordpress
# RUN     mkdir -p /var/run/nginx

# COPY conf/nginx.conf /etc/nginx/nginx.conf