FROM    alpine:3.22.0

RUN     apk update && apk upgrade && apk add mariadb mariadb-client && apk add vim

COPY    conf/50-server.cnf	/etc/my.cnf

RUN     /usr/bin/mariadb start 

# && mariadb -e "CREATE DATABASE IF NOT EXISTS \`${SQL_DATABASE}\`;" 

# \
#         && mariad -e "CREATE USER IF NOT EXISTS \`${SQL_USER}\`@'localhost' IDENTIFIED BY '${SQL_PASSWORD}';" \
#         && mariad -e "GRANT ALL PRIVILEGES ON \`${SQL_DATABASE}\`.* TO \`${SQL_USER}\`@'%' IDENTIFIED BY '${SQL_PASSWORD}';" \
#         && mariad -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${SQL_ROOT_PASSWORD}';" \
#         && mariad -e "FLUSH PRIVILEGES;" && mysqladmin -u root -p$SQL_ROOT_PASSWORD shutdown && exec mysqld_safe